"""Constants for the Heat Pump Pilot integration."""

from __future__ import annotations

DOMAIN = "heat_pump_pilot"

CONF_INDOOR_TEMP = "indoor_temp_entity"
CONF_OUTDOOR_TEMP = "outdoor_temp_entity"
CONF_PRICE_ENTITY = "price_entity"
CONF_WEATHER_FORECAST_ENTITY = "weather_forecast_entity"
CONF_CONTROLLED_ENTITY = "controlled_entity"

CONF_TARGET_TEMPERATURE = "target_temperature"
CONF_PRICE_COMFORT_WEIGHT = "price_comfort_weight"
CONF_CONTROL_INTERVAL_MINUTES = "control_interval_minutes"
CONF_PREDICTION_HORIZON_HOURS = "prediction_horizon_hours"
CONF_COMFORT_TEMPERATURE_TOLERANCE = "comfort_temperature_tolerance"
CONF_MONITOR_ONLY = "monitor_only"
CONF_VIRTUAL_OUTDOOR_HEAT_OFFSET = "virtual_outdoor_heat_offset"
CONF_HEAT_LOSS_COEFFICIENT = "heat_loss_coefficient"
CONF_THERMAL_RESPONSE_SEED = "thermal_response_seed"
CONF_INITIAL_INDOOR_TEMP = "initial_indoor_temp"
CONF_INITIAL_HEAT_GAIN = "initial_heat_gain_coefficient"
CONF_INITIAL_HEAT_LOSS_OVERRIDE = "initial_heat_loss_override"
CONF_HEATING_SUPPLY_TEMP_ENTITY = "heating_supply_temp_entity"
CONF_HEATING_SUPPLY_TEMP_THRESHOLD = "heating_supply_temp_threshold"
CONF_HEATING_DETECTION_ENABLED = "heating_detection_enabled"
CONF_HEATING_SUPPLY_TEMP_HYSTERESIS = "heating_supply_temp_hysteresis"
CONF_HEATING_SUPPLY_TEMP_DEBOUNCE_SECONDS = "heating_supply_temp_debounce_seconds"
CONF_OVERSHOOT_WARM_BIAS_ENABLED = "overshoot_warm_bias_enabled"
CONF_OVERSHOOT_WARM_BIAS_CURVE = "overshoot_warm_bias_curve"
CONF_LEARNING_SUPPLY_TEMP_ON_MARGIN = "learning_supply_temp_on_margin"
CONF_LEARNING_SUPPLY_TEMP_OFF_MARGIN = "learning_supply_temp_off_margin"
CONF_LEARNING_MODEL = "learning_model"
CONF_LEARNING_WINDOW_HOURS = "learning_window_hours"
CONF_RLS_FORGETTING_FACTOR = "rls_forgetting_factor"
CONF_PERFORMANCE_WINDOW_HOURS = "performance_window_hours"
CONF_PRICE_PENALTY_CURVE = "price_penalty_curve"
CONF_PRICE_BASELINE_WINDOW_HOURS = "price_baseline_window_hours"
CONF_PRICE_ABSOLUTE_LOW_THRESHOLD = "price_absolute_low_threshold"
CONF_PRICE_ABSOLUTE_LOW_WINDOW_DAYS = "price_absolute_low_window_days"
CONF_CONTINUOUS_CONTROL_ENABLED = "continuous_control_enabled"
CONF_CONTINUOUS_CONTROL_WINDOW_HOURS = "continuous_control_window_hours"

LEARNING_MODEL_EKF = "ekf"
LEARNING_MODEL_RLS = "rls"

DEFAULT_TARGET_TEMPERATURE = 21.0
DEFAULT_PRICE_COMFORT_WEIGHT = 0.5
DEFAULT_CONTROL_INTERVAL_MINUTES = 15
DEFAULT_PREDICTION_HORIZON_HOURS = 24
DEFAULT_COMFORT_TEMPERATURE_TOLERANCE = 1.0
DEFAULT_MONITOR_ONLY = False
DEFAULT_VIRTUAL_OUTDOOR_HEAT_OFFSET = 5.0
DEFAULT_HEAT_LOSS_COEFFICIENT = 0.05
DEFAULT_THERMAL_RESPONSE_SEED = 0.5
DEFAULT_HEATING_SUPPLY_TEMP_THRESHOLD = 30.0
DEFAULT_HEATING_DETECTION_ENABLED = True
DEFAULT_HEATING_SUPPLY_TEMP_HYSTERESIS = 1.0
DEFAULT_HEATING_SUPPLY_TEMP_DEBOUNCE_SECONDS = 60
DEFAULT_OVERSHOOT_WARM_BIAS_ENABLED = True
DEFAULT_OVERSHOOT_WARM_BIAS_CURVE = "linear"
DEFAULT_LEARNING_SUPPLY_TEMP_ON_MARGIN = 1.0
DEFAULT_LEARNING_SUPPLY_TEMP_OFF_MARGIN = 1.0
DEFAULT_LEARNING_MODEL = LEARNING_MODEL_EKF
DEFAULT_LEARNING_WINDOW_HOURS = 12
DEFAULT_RLS_FORGETTING_FACTOR = 0.99
DEFAULT_PERFORMANCE_WINDOW_HOURS = 24
DEFAULT_PRICE_PENALTY_CURVE = "linear"
DEFAULT_PRICE_RATIO_CAP = 3.0
DEFAULT_PRICE_BASELINE_WINDOW_HOURS = 24
DEFAULT_PRICE_ABSOLUTE_LOW_THRESHOLD = "auto"
DEFAULT_PRICE_ABSOLUTE_LOW_WINDOW_DAYS = 30
PRICE_ABSOLUTE_LOW_THRESHOLD_AUTO = "auto"
PRICE_ABSOLUTE_LOW_THRESHOLD_OFF = "off"
PRICE_ABSOLUTE_LOW_WINDOW_DAYS_OPTIONS = (7, 14, 30)
PRICE_BASELINE_WINDOW_OPTIONS = (24, 48, 72)
PRICE_BASELINE_FLOOR = 0.01
PRICE_RATIO_MIN = -1.0
DEFAULT_CONTINUOUS_CONTROL_ENABLED = True
DEFAULT_CONTINUOUS_CONTROL_WINDOW_HOURS = 2
CONTINUOUS_CONTROL_WINDOW_OPTIONS = (1, 2, 3, 4)

PERFORMANCE_WINDOW_OPTIONS = (6, 12, 24, 48, 72, 96)
LEARNING_WINDOW_OPTIONS = (6, 12, 24, 48)

OVERSHOOT_WARM_BIAS_CURVES = ("linear", "quadratic", "cubic", "sqrt")
PRICE_PENALTY_CURVES = ("linear", "sqrt", "quadratic")

SIGNAL_OPTIONS_UPDATED = "heat_pump_pilot_options_updated"
SIGNAL_DECISION_UPDATED = "heat_pump_pilot_decision_updated"
